### ISSUE TITLE
example.py can't find librosl.so

### ISSUE THREAD

**Issue by tjof2** [tjof2/robustpca#4]
Running on the command line `python example.py`, I get the error:

> OSError: /librosl.so.0.2: cannot open shared object file: No such file or directory

Where exactly is Python looking for the shared object file?

**Comment by bm424** [comment]
When using pyrosl as a submodule I got that same error so updated the reference as a relative path. Seems that broke it when you're running from the _same_ directory so I've now changed it to an absolute path.

**Comment by tjof2** [comment]
Right - I see what you mean, probably something to worry about once I've got the other algorithm written (and maybe then a directory structure will be useful).
